USE [TN_CSDLPT]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_KTDaThi]    Script Date: 12/16/2020 15:08:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_KTDaThi] (@MAMH NCHAR(8), @MALOP nchar(5), @LAN smallint)
RETURNS NCHAR(2)
AS
BEGIN
	DECLARE @CHECKED NCHAR(1)
	SET @CHECKED = ' '
	IF EXISTS(
	SELECT * 
	FROM dbo.BANGDIEM JOIN dbo.GIAOVIEN_DANGKY 
	ON GIAOVIEN_DANGKY.MAMH = BANGDIEM.MAMH AND GIAOVIEN_DANGKY.LAN = BANGDIEM.LAN AND BANGDIEM.MAMH = @MAMH AND MALOP = @MALOP AND BANGDIEM.LAN = @LAN)
	BEGIN
		SET @CHECKED = 'X'
		RETURN @CHECKED
	END
	RETURN @CHECKED
END
GO

