USE [TN_CSDLPT]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_KTDaThi]    Script Date: 12/21/2020 11:15:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [dbo].[FN_KTDaThi] (@MAMH NCHAR(8), @MALOP nchar(5), @LAN smallint)
RETURNS NCHAR(2)
AS
BEGIN
	DECLARE @CHECKED NCHAR(1)
	SET @CHECKED = ' '
	IF EXISTS(
	SELECT * 
	FROM dbo.BANGDIEM BD JOIN dbo.GIAOVIEN_DANGKY GVDK
	ON GVDK.MAMH = BD.MAMH AND GVDK.LAN = BD.LAN AND MASV IN(SELECT MASV FROM SINHVIEN WHERE MALOP = @MALOP) AND BD.MAMH = @MAMH AND MALOP = @MALOP AND BD.LAN = @LAN)
	BEGIN
		SET @CHECKED = 'X'
		RETURN @CHECKED
	END
	RETURN @CHECKED
END

GO

