CREATE PROCEDURE SP_CHUANBITHI (@MAMH NCHAR(5), @TRINHDO NCHAR(1), @SOCAUTHI INT)
AS
BEGIN
	DECLARE @TRINHDO_THAP NCHAR(1), @DEM1 INT, @DEM2 INT, @DEM3 INT, @DEM4 INT

	IF @TRINHDO = 'A'
	BEGIN
		SET @TRINHDO_THAP = 'B'
	END
	IF @TRINHDO = 'B'
	BEGIN
		SET @TRINHDO_THAP = 'C'
	END

	IF @TRINHDO = 'A' OR @TRINHDO = 'B' --  VI DUOI TRINH DO C KHONG CO TRINH DO NAO NUA NEN XET TRUONG HOP RIENG
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			RETURN
		END
		ELSE IF @DEM1 >= (@SOCAUTHI*0.7) -- BEN CS1 %CAU TDA >= 70%, LAY THEM CAU TDB
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE -- QUA BEN CS2 LAY THEM CAU TDA
			BEGIN
				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					RETURN
				END
				ELSE -- SO CAU TDA BEN CS2 CHUA DU LAY THEM CAU TDB
				BEGIN
					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						RETURN
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						RAISERROR('Không đủ câu hỏi thi!', 16, 1)
						RETURN
					END
				END
			END
		END
		ELSE -- BEN CS1 %CAU TDA < 70%, LAY THEM CAU TDA BEN CS2
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE IF @DEM2 >= (@SOCAUTHI*0.7 - @DEM1) -- %CAU TDA (CS1 + CS2) >= 70%, LAY CAU TDB BEN CS1 THEM
			BEGIN
				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					RETURN
				END
				ELSE -- CAU TDB BEN CS1 CHUA DU, LAY THEM CAU TDB BEN CS2
				BEGIN
					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						RETURN
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						RAISERROR('Không đủ câu hỏi thi!', 16, 1)
						RETURN
					END
				END
			END
			ELSE -- %CAU TDA (CS1 + CS2) < 70% => KHONG DU CAU THI, BAO LOI
			BEGIN
				RAISERROR('Không đủ câu hỏi thi!', 16, 1)
				RETURN
			END
		END
	END
	ELSE -- TRINH DO C
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			RETURN
		END
		ELSE IF @DEM1 >= @SOCAUTHI*0.7 -- BEN CS1 %CAU >= 70%
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= @SOCAUTHI - @DEM1 -- BEN CS2 + CS1 DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE -- KHONG DU CAU THI, BAO LOI
			BEGIN
				RAISERROR('Không đủ câu hỏi thi!', 16, 1)
				RETURN
			END
		END
		ELSE -- BEN CS1 %CAU < 70%, LAY THEM BEN CS2
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= @SOCAUTHI - @DEM1 -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE -- KHONG DU CAU THI, BAO LOI
			BEGIN
				RAISERROR('Không đủ câu hỏi thi!', 16, 1)
				RETURN
			END
		END
	END
END