USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSDKThi]    Script Date: 12/15/2020 17:17:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_DSDKThi]
	@NGAY1 DATETIME,
	@NGAY2 DATETIME
AS
BEGIN
	SELECT TENLOP, TENMH, HO + ' ' + TEN AS HOTEN, SOCAUTHI, NGAYTHI, [dbo].[FN_KTDaThi](GIAOVIEN_DANGKY.MAMH, GIAOVIEN_DANGKY.MALOP, LAN) AS DATHI
	FROM dbo.GIAOVIEN_DANGKY JOIN dbo.LOP
	ON LOP.MALOP = GIAOVIEN_DANGKY.MALOP JOIN dbo.MONHOC
	ON MONHOC.MAMH = GIAOVIEN_DANGKY.MAMH JOIN dbo.GIAOVIEN
	ON GIAOVIEN.MAGV = GIAOVIEN_DANGKY.MAGV
	AND NGAYTHI BETWEEN @NGAY1 AND @NGAY2
	ORDER BY NGAYTHI
END



GO

