USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_THONGTINDANGNHAP]    Script Date: 11/20/2020 5:26:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_THONGTINDANGNHAP]
@TENLOGIN NVARCHAR (50)
AS
DECLARE @TENUSER NVARCHAR(50)
SELECT @TENUSER = NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
 
 SELECT USERNAME = @TENUSER, 
  HOTEN = (SELECT HO + ' ' + TEN FROM dbo.GIAOVIEN  WHERE MAGV = @TENUSER),
   TENNHOM = NAME
   FROM sys.sysusers 
   WHERE UID = (SELECT GROUPUID 
                 FROM SYS.SYSMEMBERS 
                   WHERE MEMBERUID = (SELECT UID FROM sys.sysusers 
                                      WHERE NAME = @TENUSER))

GO

